  export const sign = [
    {
  /*couleurs*/
  id: 0, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'rouge',
  word: 'rouge',
  configuration: 'G',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
}, {
  id: 1, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'orange',
  word: 'orange',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
}, {
  id: 2, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'jaune',
  word: 'jaune',
  configuration: 'J',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
}, {
  id: 3, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'vert',
  word: 'vert',
  configuration: 'v',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 4, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'bleu',
  word: 'bleu',
  configuration: 'B',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 5, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'blanc',
  word: 'blanc',
  configuration: 'Paume ecartée pouce ouvert',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 6, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'noir',
  word: 'noir',
  configuration: 'N',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 7, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'gris',
  word: 'gris',
  configuration: 'G',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 8, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'sombre',
  word: 'sombre',
  configuration: ['Paume ecartée pouce ouvert', 'S'],
  configurationTwo: ['Paume ecartée pouce ouvert', 'S'],
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 9, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'clair',
  word: 'clair',
  configuration: ['S', 'Paume ecartée pouce ouvert'],
 configurationTwo: ['S', 'Paume ecartée pouce ouvert'],
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 10, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'transparent',
  word: 'transparent',
  configuration: 'Paume ecartée pouce fermé',
  configurationTwo: 'Paume ecartée pouce fermé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 11, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'marron',
  word: 'marron',
  configuration: 'S',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 12, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'rose',
  word: 'rose',
  configuration: 'R',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
/*famille*/
{
  id: 13, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'bebe',
  word: 'bébé',
  configuration: 'Canard',
configurationTwo: 'Canard',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 14, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'cousin',
  word: 'cousin',
  configuration: 'C',
  configurationTwo: 'C',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 15, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'enfants',
  word: 'enfants',
  configuration: 'Canard',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 16, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'famille',
  word: 'famille',
  configuration: ['Paume ecartée pouce ouvert', 'Canard'],
  configurationTwo: ['Paume ecartée pouce ouvert', 'Canard'],
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 17, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'femme',
  word: 'femme',
  configuration: 'G',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 18, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'fils',
  word: 'fils',
  configuration: ['Pince', 'Paume ecartée pouce ouvert'],
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 19, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'frere',
  word: 'frère',
  configuration: 'F',
 configurationTwo: 'F',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 20, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'garcon',
  word: 'garçon',
  configuration: 'A',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 21, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'grand-mere',
  word: 'grand mère',
  configuration: ['A', 'R'],
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 22, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'grand-parents',
  word: 'grand parents',
  configuration: ['Pince', 'A', 'S'],
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 23, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'grand-pere',
  word: 'grand père',
  configuration: ['Pince', 'S'],
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 24, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'homme',
  word: 'homme',
  configuration: 'Pince',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 25, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'maman',
  word: 'maman',
  configuration: 'A',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 26, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'mere',
  word: 'mère',
  configuration: 'A',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 27, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'papa',
  word: 'papa',
  configuration: 'Pince',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 28, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'parents',
  word: 'parents',
  configuration: ['Pince','A'],
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 29, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'soeur',
  word: 'soeur',
  configuration: 'S',
 configurationTwo: 'S',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 30, 
  category: 'signe-',
  type: 'nom',
  function: 'famille',
  url: 'tante',
  word: 'tante',
  configuration: 'T',
 configurationTwo: 'T',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
/*verbes*/
{
  id: 31, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'trier',
  word: 'trier',
  configuration: 'Paume pouce fermé',
 configurationTwo: 'Paume pouce fermé',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 32, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'transferer',
  word: 'transférer',
  configuration: ['Paume pouce ouvert', 'Canard'],
  configurationTwo: ['Paume pouce ouvert', 'Canard'],
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 33, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'supprimer',
  word: 'supprimer',
  configuration: 'A',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 34, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'suivre',
  word: 'suivre',
  configuration: 'A',
  configurationTwo: 'A',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 35, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'separer',
  word: 'séparer',
  configuration: 'S',
  configurationTwo: 'S',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 36, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'reparer',
  word: 'réparer',
  configuration: 'U',
  configurationTwo: 'U',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 37, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'projeter',
  word: 'projeter',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 38, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'organiser',
  word: 'organiser',
  configuration: 'S',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 39, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'modifier',
  word: 'modifier',
  configuration: 'clé',
  configurationTwo: 'clé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 40, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'livrer',
  word: 'livrer',
  configuration: 'Paume pouce fermé',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 41, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'effacer',
  word: 'effaçer',
  configuration: 'S',
  configurationTwo: 'S',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 42, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'corriger',
  word: 'corriger',
  configuration: 'G',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 43, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'copier',
  word: 'copier',
  configuration: 'Canard',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 44, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'calculer',
  word: 'calculer',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'Paume pouce ouvert',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 45, 
  category: 'signe-',
  type: 'verbe',
  function: 'organiser',
  url: 'argumenter',
  word: 'argumenter',
  configuration: 'G',
  configurationTwo: 'G',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
/*temps*/
{
  id: 46, 
  category: 'signe-',
  type: 'verbe',
  function: 'temps',
  url: 'annee',
  word: 'année',
  configuration: 'S',
 configurationTwo: 'S',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 47, 
  category: 'signe-',
  type: 'verbe',
  function: 'temps',
  url: 'jour',
  word: 'jour',
  configuration: 'G',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 48, 
  category: 'signe-',
  type: 'verbe',
  function: 'temps',
  url: 'mois',
  word: 'mois',
  configuration: 'A',
configurationTwo: 'Paume pouce fermé',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
/*jour*/
{
  id: 49, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'lundi',
  word: 'lundi',
  configuration: 'L',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 50, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'mardi',
  word: 'mardi',
  configuration: 'A',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 51, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'mercredi',
  word: 'mercredi',
  configuration: 'E',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 52, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'jeudi',
  word: 'jeudi',
  configuration: 'J',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 53, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'vendredi',
  word: 'vendredi',
  configuration: 'V',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 54, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'samedi',
  word: 'samedi',
  configuration: 'S',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 55, 
  category: 'signe-',
  type: 'verbe',
  function: 'jour',
  url: 'dimanche',
  word: 'dimanche',
  configuration: 'D',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
/*mois*/
{
  id: 56, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'janvier',
  word: 'janvier',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 57, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'fevrier',
  word: 'février',
  configuration: 'Paume pouce fermé',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 58, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'mars',
  word: 'mars',
  configuration: 'Pince pliée',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 59, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'avril',
  word: 'avril',
  configuration: 'Paume pouce fermé',
 configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 60, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'mai',
  word: 'mai',
  configuration: 'G',
  configurationTwo: 'none',
  ovement: true,
  movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 61, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'juin',
  word: 'juin',
  configuration: 'G',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 62, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'juillet',
  word: 'juillet',
  configuration: 'G',
  configurationTwo: 'G',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 63, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'aout',
  word: 'août',
  configuration: 'Paume pouce ouvert',
configurationTwo: 'none',
  movement: true,
 movementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 64, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'septembre',
  word: 'septembre',
  configuration: 'Ok',
  configurationTwo: 'Ok',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 65, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'octobre',
  word: 'octobre',
  configuration: 'O',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 66, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'novembre',
  word: 'novembre',
  configuration: 'N',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},{
  id: 67, 
  category: 'signe-',
  type: 'nom',
  function: 'mois',
  url: 'decembre',
  word: 'décembre',
  configuration: 'D',
  configurationTwo: 'none',
  movement: true,
  ovementType: 'tap',
  movementDirection: 'back and forth'
},
{
  id: 68, 
  category: 'signe-',
  type: 'nom',
  function: 'temps',
  url: 'siecle',
  word: 'siècle',
  configuration: 'S',
  configurationTwo: 'S',
  movement: true,
  ovementType: 'slideBack',
  movementDirection: 'back and forth'
},
{
  id: 69, 
  category: 'signe-',
  type: 'nom',
  function: 'couleur',
  url: 'violet',
  word: 'violet',
  configuration: 'V',
  configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 70, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'cheval',
  word: 'cheval',
  configuration: 'V',
  configurationTwo: 'V',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 71, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'coq',
  word: 'coq',
  configuration: '3',
  configurationTwo: 'none',
  movement: true,
  movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 72, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'poule',
  word: 'poule',
  configuration: 'pince',
  configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 73, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'souris',
  word: 'souris',
  configuration: 'U',
  configurationTwo: 'S',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 74, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'poisson',
  word: 'poisson',
  configuration: 'Paume',
  configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 75, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'chat',
  word: 'chat',
  configuration: ['S', '3'],
configurationTwo: ['S', '3'],
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 76, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'chien',
  word: 'chien',
  configuration: 'Paume pouce ouvert',
 configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{/*aaaaaaa*/
  id: 77, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'moustique',
  word: 'moustique',
  configuration: 'Pince',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 78, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'animal',
  word: 'animal',
  configuration: 'Paume écartée pouce ouvert',
  configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 79, 
  category: 'signe-',
  type: 'nom',
  function: 'animal',
  url: 'lapin',
  word: 'lapin',
  configuration: 'Double L',
 configurationTwo: 'Double L',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 80, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'peinture',
  word: 'peinture',
  configuration: 'Double L',
  configurationTwo: 'Paume pouce ouvert',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 81, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'film',
  word: 'film',
  configuration: 'G',
configurationTwo: 'G',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 82, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'lecture',
  word: 'lecture',
  configuration: 'V',
  configurationTwo: 'Paume pouce ouvert',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 83, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'culture',
  word: 'culture',
  configuration: 'Majeur',
  configurationTwo: 'Majeur',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 84, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'photographie',
  word: 'photographie',
  configuration: ['L', 'Pince'],
  configurationTwo: ['L', 'Pince'],
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 85, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'art',
  word: 'art',
  configuration: ['S', 'Paume écartée pouce ouvert'],
  configurationTwo: 'none',
  movement: true,
  movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 86, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'jeu-video',
  word: 'jeu vidéo',
  configuration: ['J', 'S'],
  configurationTwo: ['J', 'S'],
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 87, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'zoo',
  word: 'zoo',
  configuration: ['Z', 'O'],
  configurationTwo: 'none',
  movement: true,
  movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 88, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'parc',
  word: 'parc',
  configuration: 'V',
configurationTwo: 'V',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 89, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'boite-de-nuit',
  word: 'boîte de nuit',
  configuration: 'Poing',
  configurationTwo: 'Poing',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 90, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'chant',
  word: 'chant',
  configuration: 'Paume écartée pouce ouvert',
 configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 91, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'theatre',
  word: 'théâtre',
  configuration: 'Majeur',
  configurationTwo: 'Majeur',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 92, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'cinema',
  word: 'cinéma',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'Paume pouce ouvert',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 93, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'bibliotheque',
  word: 'bibliothèque',
  configuration: 'Paume pouce ouvert',
  configurationTwo: 'Paume pouce ouvert',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 94, 
  category: 'signe-',
  type: 'nom',
  function: 'loisir',
  url: 'loisir',
  word: 'loisir',
  configuration: 'Paume écartée pouce ouvert',
  configurationTwo: 'none',
  movement: true,
   movementType: 'slideDown',
  movementDirection: 'diagonal'
},{
  id: 95, 
  category: 'signe-',
  type: 'nom',
  function: 'lieu',
  url: 'universite',
  word: 'université',
  configuration: 'U',
  configurationTwo: 'Paume pouce fermé',
  movement: true,
   movementType: 'turn',
  movementDirection: 'static'
} ];

 
